# Generated by Django 5.2.3 on 2025-07-17 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbies',
            name='quiz_id',
        ),
        migrations.AlterUniqueTogether(
            name='usersonquizes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.AddField(
            model_name='lobbies',
            name='category',
            field=models.CharField(default='random', max_length=16),
        ),
        migrations.AddField(
            model_name='lobbies',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'легкая'), ('medium', 'средняя'), ('hard', 'высокая'), ('mixed', 'смешанная')], default='mixed'),
        ),
        migrations.AddField(
            model_name='lobbies',
            name='title',
            field=models.CharField(default='Quizl', max_length=32),
        ),
        migrations.AddField(
            model_name='users',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersonquizes',
            name='category',
            field=models.CharField(default='random', max_length=16),
        ),
        migrations.AddField(
            model_name='usersonquizes',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'легкая'), ('medium', 'средняя'), ('hard', 'высокая'), ('mixed', 'смешанная')], default='mixed'),
        ),
        migrations.AlterField(
            model_name='usersonquizes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='usersonquizes',
            name='quiz_id',
        ),
        migrations.DeleteModel(
            name='Quizes',
        ),
    ]
